### ISSUE TITLE
DragonTravel breaks //set in WorldEdit

### ISSUE THREAD

**Issue by Tachyon42** [Phiwa/DragonTravel#35] opened 2016-10-23 18:40 UTC
//set no longer works in WorldEdit when DragonTravel is loaded.

http://pastebin.com/9XmA5LRq <- output from console on using //set

worldedit-bukkit-6.1.3.jar and DragonTravel-01.005.01.jar are the versions in use. Those in the Worldedit support IRC channel assure me the problem is due to DragonTravel and the way it interacts with the WorldEdit API.

**Comment by kenzierocks** [comment] 2016-10-23 18:49
To clarify: The problem is "command-framework-bukkit", it shares some class names with the WorldEdit command system (probably because it is a subset of the WE command system) but they differ from the current implementations. You either need to perform relocation when shading this library or switch to using [Intake](https://github.com/sk89q/Intake), which I believe to be the updated version of "command-framework-bukkit."

**Comment by Phiwa** [comment] 2016-10-23 19:33
I just wanted to ask why we got problems with WorldEdit, but yes, we are using the old command framework. I'll take a look at the, but that will not be possible within the next two weeks, sorry.

Thanks for the report!

**Comment by Phiwa** [comment] 2016-11-04 21:39
Should be solved with commit 986a2ea0bd589181d844861d36d84817a5e064c7, thanks again for the report. Fix will be included in next version.

**Closed by Phiwa** 2016-11-04 21:39 UTC
